### ISSUE TITLE
[Bug] 无法正常保存表情包 

### ISSUE THREAD

**Issue by maoxig** [colasama/nonebot-plugin-sticker-saver#1]
**描述问题**

似乎是短链接失效，无论是保存 图片、表情包还是gif都无法正常使用

**期望的结果**

正常保存，最好优化一下逻辑，gif的逻辑应与普通图片分开处理，避免链接失效影响到正常的表情包保存

环境信息**

OS: termux + Ubuntu 22.04 arm64
Python Version: 3.10.12
Nonebot Version: v2.2.1
httpx Version: 0.23.3
适配器: onbot.V11

**复现条件**

使用指令保存时即可复现
![8ba96848ced6d76c0d697dd9d8e4ce16](https://github.com/colasama/nonebot-plugin-sticker-saver/assets/123555887/666ac716-1e81-442e-a21a-16dac4d0d57e)
![SAVE_20240516_170613](https://github.com/colasama/nonebot-plugin-sticker-saver/assets/123555887/3cb691f5-20cf-461b-9cce-01baebb39800)

**Comment by colasama** [comment]
不好意思最近比较忙刚刚看到！我去瞅瞅

**Comment by colasama** [comment]
已修复，可以测试一下~ 如果还有问题的话欢迎继续提 issue（？
