### ISSUE TITLE
提示 未在回复内容中检测到表情...

### ISSUE THREAD

**Issue by hakureireimusama** [colasama/nonebot-plugin-sticker-saver#2]
![image](https://github.com/user-attachments/assets/b8db17f5-984f-4904-9248-1e26d2c9968b)

**Comment by colasama** [comment]
不好意思现在才看到！之前的话 `go-cqhttp` 是获取不到下载 / 购买的 QQ 表情包的，但是换成 `NapCat` 之后好像就可以了，如果还不行的话请问方便提供一下表情来源么？
